- name: Open required ports
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
  loop:
    - "{{ wazuh_agent_port }}"
    - "{{ wazuh_api_port }}"
    - "{{ wazuh_dashboard_port }}"
    - "{{ wazuh_indexer_port }}"