- name: Add GPG key (Debian)
  ansible.builtin.apt_key:
    url: "{{ wazuh_repo_gpg_key_url }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Add repo (Debian)
  ansible.builtin.apt_repository:
    repo: "{{ wazuh_repo_url_debian }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Add repo (RHEL)
  ansible.builtin.yum_repository:
    name: wazuh
    baseurl: "{{ wazuh_repo_url_rhel }}"
    gpgkey: "{{ wazuh_repo_gpg_key_url }}"
    enabled: true
  when: ansible_os_family == "RedHat"

- name: Install Wazuh Manager
  ansible.builtin.package:
    name: wazuh-manager
    state: present
  when: wazuh_manager_enabled | bool

- name: Install Wazuh Indexer
  ansible.builtin.package:
    name: wazuh-indexer
    state: present
  when: wazuh_indexer_enabled | bool

- name: Install Wazuh Dashboard
  ansible.builtin.package:
    name: wazuh-dashboard
    state: present
  when: wazuh_dashboard_enabled | bool
