
- name: Validate configuration
  ansible.builtin.include_tasks: validate.yml

- name: Install Wazuh components
  ansible.builtin.include_tasks: install.yml

- name: Generate Wazuh certificates
  ansible.builtin.include_tasks: certs.yml
  when: wazuh_tls_enabled | bool

- name: Configure components
  ansible.builtin.include_tasks: configure.yml

- name: Initialize security index
  ansible.builtin.include_tasks: security.yml

- name: Configure services
  ansible.builtin.include_tasks: service.yml

- name: Configure Wazuh API RBAC
  ansible.builtin.include_tasks: rbac_api.yml
  when: wazuh_api_rbac_enabled | bool

- name: Configure Wazuh Dashboard RBAC
  ansible.builtin.include_tasks: rbac_dashboard.yml
  when: wazuh_dashboard_rbac_enabled | bool

- name: Perform health checks
  ansible.builtin.include_tasks: verify.yml