- name: Add GPG key (Debian)
  ansible.builtin.apt_key:
    url: "{{ wazuh_repo_gpg_key_url }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Add repo (Debian)
  ansible.builtin.apt_repository:
    repo: "{{ wazuh_repo_url_debian }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Add repo (RHEL)
  ansible.builtin.yum_repository:
    name: wazuh
    baseurl: "{{ wazuh_repo_url_rhel }}"
    gpgkey: "{{ wazuh_repo_gpg_key_url }}"
    enabled: true
  when: ansible_os_family == "RedHat"