---

# =====================================================
# Wait for Indexer Port
# =====================================================

- name: Wait for Wazuh Indexer to start
  ansible.builtin.wait_for:
    host: "{{ wazuh_runtime_host }}"
    port: "{{ wazuh_indexer_port }}"
    timeout: 300
  when:
    - wazuh_indexer_enabled | bool


# =====================================================
# Check Security Initialization
# =====================================================

- name: Check if security already initialized
  ansible.builtin.uri:
    url: "https://{{ wazuh_runtime_host }}:{{ wazuh_indexer_port }}"
    method: GET
    validate_certs: no
    status_code: [200,401,503]
  register: security_status
  failed_when: false
  when:
    - wazuh_indexer_enabled | bool


# =====================================================
# Initialize Security Index
# =====================================================

- name: Initialize Wazuh Indexer security
  ansible.builtin.command: >
    /usr/share/wazuh-indexer/bin/indexer-security-init.sh
  register: security_init
  changed_when: "'Security Admin v' in security_init.stdout"
  when:
    - wazuh_tls_enabled | bool
    - wazuh_indexer_enabled | bool
    - security_status.status == 503


# =====================================================
# Push Security Configuration (IMPORTANT)
# =====================================================

# =====================================================
# Apply OpenSearch Security Configuration
# =====================================================

- name: Apply OpenSearch security configuration
  ansible.builtin.command: >
    /usr/share/wazuh-indexer/plugins/opensearch-security/tools/securityadmin.sh
    -cd /etc/wazuh-indexer/opensearch-security
    -key {{ wazuh_tls_admin_key_file }}
    -cert {{ wazuh_tls_admin_cert_file }}
    -cacert {{ wazuh_tls_ca_file }}
    -icl -nhnv
  environment:
    OPENSEARCH_JAVA_HOME: /usr/share/wazuh-indexer/jdk
    JAVA_HOME: /usr/share/wazuh-indexer/jdk
  register: security_apply
  changed_when: "'Done with success' in security_apply.stdout"
  when:
    - wazuh_tls_enabled | bool
    - wazuh_indexer_enabled | bool

# =====================================================
# Restart Indexer
# =====================================================

- name: Restart wazuh-indexer after security config
  ansible.builtin.service:
    name: wazuh-indexer
    state: restarted
  when:
    - wazuh_tls_enabled | bool
    - wazuh_indexer_enabled | bool


# =====================================================
# Wait Again After Restart
# =====================================================

- name: Wait for Wazuh Indexer after restart
  ansible.builtin.wait_for:
    host: "{{ wazuh_runtime_host }}"
    port: "{{ wazuh_indexer_port }}"
    timeout: 300
  when:
    - wazuh_tls_enabled | bool
    - wazuh_indexer_enabled | bool