- name: Render systemd service
  ansible.builtin.template:
    src: systemd.j2
    dest: "{{ wazuh_service_file }}"
    owner: root
    group: root
    mode: "0644"

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable & start services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - wazuh-manager
    - wazuh-indexer
    - wazuh-dashboard